services:
  api:
    build: .
    image: lfdig/youtube-downloader-api
    container_name: nest_youtube_api
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./downloads:/usr/src/app/downloads
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis_youtube_downloader